runtime: nodejs16
instance_class: F2
env: standard

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5